name: "Demo"

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - 'k8s/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - name: "test run"
        run: ls 