name: "Deploy glu on k8s to segment"
on:
  workflow_dispatch:
    inputs:
      segment:
        description: 'Segment on which we deploy k8s files'
        required: true
        type: choice
        options:
          - dev00
          - dev01
          - ci00
          - pro00
      ref:
        description: "hello"
        required: true
        type: string
jobs:
  test_echo:
    runs-on: ubuntu-latest
    steps: 
      - name: Echo upper case
        shell: bash
        run: |
          INPUT_SEGMENT=${{ inputs.segment }}
          echo "SEGMENT_UPPER=${INPUT_SEGMENT@U}" >> ${GITHUB_ENV}
      - name: echo environment variable
        run: |
          echo ${{ env.SEGMENT_UPPER }}


  
        
        
